name: Database Lint

on:
  pull_request_target:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - id: nodeversion
        run: echo "NODE=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: restore Cache
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js ${{steps.nodeversion.outputs.NODE}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nodeversion.outputs.NODE }}
      - name: install
        run: |
          yarn
      - name: lint
        run: |
          yarn lint
      - name: Test generation
        env:
          G_API_KEY: ${{ secrets.G_API_KEY }}
        run: |
          node src/generate.js test
